// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dgV00Ym2L48-M74HuHIzrFxs0I0Kvco',
    appId: '1:139315620003:android:33cb2b6b391372cbe47716',
    messagingSenderId: '139315620003',
    projectId: 'processingpro-5daf6',
    storageBucket: 'processingpro-5daf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWg2bzraq0Mm_F1-adS4Mo7t58pWCDFOU',
    appId: '1:139315620003:ios:88b118c433118e23e47716',
    messagingSenderId: '139315620003',
    projectId: 'processingpro-5daf6',
    storageBucket: 'processingpro-5daf6.appspot.com',
    androidClientId: '139315620003-3v79u6rcrrohbkmpbkqk6sa6u3fg218e.apps.googleusercontent.com',
    iosClientId: '139315620003-l0p8jnuu23ibhkffrkg37vricb5gt0pl.apps.googleusercontent.com',
    iosBundleId: 'com.processing.cryptoApp',
  );
}
